### ISSUE TITLE
v1.0  led_buitin

### ISSUE THREAD

**Issue by J4e8a16n** [m1cr0lab-esp32/remote-control-with-websocket#3]
Hi,

Missing  #define LED_BUILTIN  2
in v1.0

Apart this everything runs ok in platformio.

Regards

JPD

**Comment by m1cr0lab** [comment]
Hi Jean-Pierre,

This is a constant [predefined](https://github.com/espressif/arduino-esp32/blob/b92c58d74b151c7a3b56db4e78f2d3c90c16446f/variants/doitESP32devkitV1/pins_arduino.h#L14) by the **arduino-esp32** core for the **doitESP32devkitV1** board ;-)
