### ISSUE TITLE
v1.1

### ISSUE THREAD

**Issue by J4e8a16n** [m1cr0lab-esp32/remote-control-with-websocket#4]
Hi,

How can I create a v1.1 for mysels   in platformio

git add myNotes.md
git stash
git  commit  -m   "my file added"

?

Regards 

JPD

**Comment by m1cr0lab** [comment]
Hi Jean-Pierre,

Assuming that you cloned the repository:

```
git clone https://github.com/m1cr0lab-esp32/remote-control-with-websocket.git
```

Once you have created your myNotes.md file and added content:

```
git add myNotes.md
git commit -m "adds myNotes.md file"
git tag v1.1
```

Now to view all the tags listed:

```
git tag --list -n1
```

And you should get:

```
v0.0            Project Bootstrap
v0.1            LED Setup
v0.2            Button Setup
v0.3            Web UI Design
v0.4            SPIFFS Setup
v0.5            WiFi Setup
v0.6            Web Server Setup
v0.7            WebSocket Setup
v0.8            WebSocket Data Exchange
v1.0            WebSocket and JSON
v1.1            adds myNotes.md file
```

Cheers,
Steph

**Comment by J4e8a16n** [comment]
Success.  Thanks



Hi Jean-Pierre,
Assuming that you cloned the repository:
git clone https://github.com/m1cr0lab-esp32/remote-control-with-websocket.git

Once you have created your myNotes.md file and added content:
git add myNotes.md
git commit -m "adds myNotes.md file"
git tag v1.1

Now to view all the tags listed:
git tag --list -n1

And you should get:
v0.0            Project Bootstrap
v0.1            LED Setup
v0.2            Button Setup
v0.3            Web UI Design
v0.4            SPIFFS Setup
v0.5            WiFi Setup
v0.6            Web Server Setup
v0.7            WebSocket Setup
v0.8            WebSocket Data Exchange
v1.0            WebSocket and JSON
v1.1            adds myNotes.md file

Cheers,
Steph
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
